//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nedeljni1_Andreja_Kolesar.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdministrator
    {
        public int administratorId { get; set; }
        public System.DateTime expiryDate { get; set; }
        public int adminTypeId { get; set; }
        public int userId { get; set; }
    
        public virtual tblAdminType tblAdminType { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
