//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nedeljni1_Andreja_Kolesar.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDailyReport
    {
        public int reportId { get; set; }
        public System.DateTime reportDate { get; set; }
        public string description { get; set; }
        public int workingHours { get; set; }
        public Nullable<int> employeeId { get; set; }
        public Nullable<int> projectId { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual tblProject tblProject { get; set; }
    }
}
