//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nedeljni1_Andreja_Kolesar.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProject()
        {
            this.tblDailyReports = new HashSet<tblDailyReport>();
        }
    
        public int projectId { get; set; }
        public string projectName { get; set; }
        public string description { get; set; }
        public string clientName { get; set; }
        public System.DateTime contractDate { get; set; }
        public int contractManagerId { get; set; }
        public System.DateTime startingDate { get; set; }
        public System.DateTime deadline { get; set; }
        public decimal hourlyRate { get; set; }
        public string realisation { get; set; }
        public int leaderId { get; set; }
        public Nullable<int> employee1 { get; set; }
        public Nullable<int> employee2 { get; set; }
        public Nullable<int> employee3 { get; set; }
        public Nullable<int> employee4 { get; set; }
        public Nullable<int> employee5 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDailyReport> tblDailyReports { get; set; }
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual tblEmployee tblEmployee1 { get; set; }
        public virtual tblEmployee tblEmployee2 { get; set; }
        public virtual tblEmployee tblEmployee3 { get; set; }
        public virtual tblEmployee tblEmployee4 { get; set; }
        public virtual tblManager tblManager { get; set; }
        public virtual tblManager tblManager1 { get; set; }
    }
}
