//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nedeljni1_Andreja_Kolesar.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUser()
        {
            this.tblAdministrators = new HashSet<tblAdministrator>();
            this.tblEmployees = new HashSet<tblEmployee>();
            this.tblManagers = new HashSet<tblManager>();
        }
    
        public int userId { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string jmbg { get; set; }
        public Nullable<int> genderId { get; set; }
        public string residence { get; set; }
        public Nullable<int> marriageStatusId { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAdministrator> tblAdministrators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployee> tblEmployees { get; set; }
        public virtual tblGender tblGender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblManager> tblManagers { get; set; }
        public virtual tblMarriageStatu tblMarriageStatu { get; set; }
    }
}
