//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nedeljni1_Andreja_Kolesar.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAdministrator
    {
        public int userId { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string jmbg { get; set; }
        public Nullable<int> genderId { get; set; }
        public string residence { get; set; }
        public Nullable<int> marriageStatusId { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int administratorId { get; set; }
        public int adminTypeId { get; set; }
        public System.DateTime expiryDate { get; set; }
        public string status { get; set; }
        public string gender { get; set; }
        public string typeName { get; set; }
    }
}
