//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nedeljni1_Andreja_Kolesar.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEmployee
    {
        public int userId { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string jmbg { get; set; }
        public Nullable<int> genderId { get; set; }
        public string residence { get; set; }
        public Nullable<int> marriageStatusId { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int employeeId { get; set; }
        public Nullable<int> managerId { get; set; }
        public Nullable<int> positionID { get; set; }
        public int qualificationsId { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public int sectorId { get; set; }
        public int yearsOfService { get; set; }
        public string status { get; set; }
        public string gender { get; set; }
        public string sectorName { get; set; }
        public string positionName { get; set; }
        public string qualification { get; set; }
    }
}
